language: cpp
compiler: gcc
install: cmake

before_install:
   - sudo apt-get -qq update
   - sudo apt-get install -y libgtest-dev valgrind
   - sudo wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz
   - sudo tar xf release-1.7.0.tar.gz
   - cd googletest-release-1.7.0
   - sudo cmake -DBUILD_SHARED_LIBS=ON .
   - sudo make
   - sudo cp -a include/gtest /usr/include
   - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
   - which valgrind
   - cd "${TRAVIS_BUILD_DIR}"
before_script:
   - make
   - cd testing
   - cmake -Dtest=ON ../
   - make
   - ls -l

script: ./runTests.out
